### PR TITLE
logo

### PR DESCRIPTION
**Pull request by yhoogstrate**
Please sign off by admins only
------------------------------

ping @shiltemann

### CODE REVIEW

**Comment by yhoogstrate** [comment]
Pong @shiltemann

**Comment by shiltemann** [comment]
:+1:

**Comment by shiltemann** [comment]
now just hope IUC doesn't sue us for copyright infringement ;P

**Comment by yhoogstrate** [comment]
MIT permits this, I carefully read it trough. Thanks Saskia

**Pull request merged**
