### PR TITLE
probably needs updated test data but planemo does not work at arch to…

### PR DESCRIPTION
**Pull request by yhoogstrate**
…day...

Please sign off by admins only
------------------------------

* [x] Has no duplicate (otherwise merge required)
* [ ] Indentation is correct
* [x] Tests
  - [x] Parameters are reasonably covered
  - [x] Test files are appropriate
* [x] `<command/>`: file names are escaped
* [x] Tool requires version/build increase
* [x] Toolshed user `erasmus-medical-center` has access to associated toolshed repo(s)

### CODE REVIEW

**Comment by yhoogstrate** [comment]
@shiltemann is er iets fout gegaan met de laatste travis update?

**Comment by shiltemann** [comment]
nee, bij eerste push van nieuwe branch (of force push van existing) gebeurt dat, volgende commit werkt het weer

**Comment by shiltemann** [comment]
yep, nu komt ie verder

**Comment by yhoogstrate** [comment]
Bedankt!! 😆

**Pull request merged**
